/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.vsolicitudesweb;
import Logica.fsolicitudesweb;
import java.sql.Date;

import javaemail.Correo;

import javax.swing.JOptionPane;


/**
 *
 * @author inesm
 */
public class frmGestionweb extends javax.swing.JInternalFrame {

	/**
	 * Creates new form frmGestionweb
	 */
	public frmGestionweb() {
		initComponents();
		inhabilitar();
	}

	void inhabilitar() {
		txtsolicitud.setEnabled(false);
		txtnum.setEnabled(false);
		txttipo.setEnabled(false);
		txtFein.setEnabled(false);
		txtfesa.setEnabled(false);
		
		txtemail.setVisible(false);
		
		txtidaparta.setVisible(false);
		
		txtmsgdisp.setVisible(false);
		
		chbdispo.setVisible(true);
		
		chbemaila.setVisible(false);
		
		chbemaild.setVisible(false);
		
		lblcliente.setVisible(false);
		
		lblasunto.setVisible(false);
		
		lblmensaje.setVisible(false);
		
		txtdestino.setVisible(false);
		
		txtasunto.setVisible(false);
		jSCP1.setVisible(false);
		txtAmensaje.setVisible(false);
		
		btnenviar.setVisible(false);

	}

	void habilitar() {
		
		txtmsgdisp.setVisible(true);
		chbemaila.setVisible(true);
		chbemaild.setVisible(true);
		chbdispo.setVisible(true);
		chbdispo.setSelected(true);
		
	

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtsolicitud = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txttipo = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txtnum = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                txtFein = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                txtfesa = new javax.swing.JTextField();
                jSeparator1 = new javax.swing.JSeparator();
                chbdispo = new javax.swing.JCheckBox();
                txtmsgdisp = new javax.swing.JTextField();
                chbemaila = new javax.swing.JCheckBox();
                jSeparator2 = new javax.swing.JSeparator();
                chbemaild = new javax.swing.JCheckBox();
                lblcliente = new javax.swing.JLabel();
                txtdestino = new javax.swing.JTextField();
                lblasunto = new javax.swing.JLabel();
                txtasunto = new javax.swing.JTextField();
                jSCP1 = new javax.swing.JScrollPane();
                txtAmensaje = new javax.swing.JTextArea();
                lblmensaje = new javax.swing.JLabel();
                btnenviar = new javax.swing.JButton();
                txtidaparta = new javax.swing.JTextField();
                txtemail = new javax.swing.JTextField();

                setBackground(new java.awt.Color(255, 255, 204));
                setClosable(true);
                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setIconifiable(true);
                setMaximizable(true);

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/Brasilia13.png"))); // NOI18N

                jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 153, 204));
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Gestionando Solicitud-Reserva WEB");

                jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(0, 153, 204));
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("# SolicitudWeb:");

                jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(0, 153, 204));
                jLabel4.setText("Tipo-Apto:");

                txttipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

                jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(0, 153, 204));
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("# Apto:");

                jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(0, 153, 204));
                jLabel6.setText("FechaIngreso-Deseada:");

                jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(0, 153, 204));
                jLabel7.setText("FechaSalida-Deseada:");

                chbdispo.setForeground(new java.awt.Color(0, 153, 204));
                chbdispo.setText("VERIFICANDO DISPONIBILIDAD REAL.");
                chbdispo.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                chbdispoItemStateChanged(evt);
                        }
                });
                chbdispo.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                chbdispoStateChanged(evt);
                        }
                });
                chbdispo.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                chbdispoMouseClicked(evt);
                        }
                });
                chbdispo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chbdispoActionPerformed(evt);
                        }
                });

                txtmsgdisp.setForeground(new java.awt.Color(0, 153, 204));
                txtmsgdisp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                txtmsgdisp.setOpaque(false);

                chbemaila.setForeground(new java.awt.Color(0, 153, 204));
                chbemaila.setText("RESPONDER SOLICITUD AHORA");
                chbemaila.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                chbemailaItemStateChanged(evt);
                        }
                });
                chbemaila.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                chbemailaMouseClicked(evt);
                        }
                });
                chbemaila.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chbemailaActionPerformed(evt);
                        }
                });

                chbemaild.setForeground(new java.awt.Color(0, 153, 204));
                chbemaild.setText("RESPONDER SOLICITUD DESPUES");
                chbemaild.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chbemaildActionPerformed(evt);
                        }
                });

                lblcliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                lblcliente.setForeground(new java.awt.Color(0, 153, 204));
                lblcliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblcliente.setText("CLIENTE:");

                lblasunto.setForeground(new java.awt.Color(0, 153, 204));
                lblasunto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblasunto.setText("ASUNTO:");

                txtAmensaje.setColumns(20);
                txtAmensaje.setRows(5);
                txtAmensaje.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                txtAmensaje.setEnabled(false);
                jSCP1.setViewportView(txtAmensaje);

                lblmensaje.setForeground(new java.awt.Color(0, 153, 204));
                lblmensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblmensaje.setText("MENSAJE:");

                btnenviar.setText("ENVIAR");
                btnenviar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnenviarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtsolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(txtFein))
                                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(txtfesa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(26, 26, 26)
                                                                                                                .addComponent(txtidaparta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)))))))))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(77, 77, 77)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(chbdispo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(chbemaila, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(txtmsgdisp, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(chbemaild, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jSeparator2)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblasunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                        .addComponent(lblmensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtdestino)
                                                        .addComponent(txtasunto)
                                                        .addComponent(jSCP1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(15, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnenviar)
                                .addGap(25, 25, 25))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel3)
                                                                .addComponent(txtsolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtFein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtfesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtidaparta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chbdispo)
                                        .addComponent(txtmsgdisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chbemaila)
                                        .addComponent(chbemaild))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblasunto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtasunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(115, 115, 115))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSCP1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)))
                                .addComponent(btnenviar)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void chbdispoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbdispoMouseClicked
	
        }//GEN-LAST:event_chbdispoMouseClicked

        private void chbdispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbdispoActionPerformed
                // TODO add your handling code here:
	
        }//GEN-LAST:event_chbdispoActionPerformed

        private void chbdispoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbdispoStateChanged
                // TODO add your handling code here:
		

        }//GEN-LAST:event_chbdispoStateChanged

        private void chbdispoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbdispoItemStateChanged
                // TODO add your handling code here:
		fsolicitudesweb func = new fsolicitudesweb();
		int idap = Integer.parseInt(txtidaparta.getText());
		
		Date FeID =Date.valueOf(txtFein.getText());
		if (func.disponi(idap, FeID)) {
			habilitar();
			txtmsgdisp.setText("ES FACTIBLE LA RESERVA EN ESAS FECHAS");
			
		} else {
			habilitar();
			txtmsgdisp.setText("NO ES FACTIBLE LA RESERVA EN ESAS FECHAS");
			
		}		

        }//GEN-LAST:event_chbdispoItemStateChanged

        private void chbemailaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbemailaItemStateChanged
                // TODO add your handling code here:
		txtmsgdisp.setVisible(false);
		chbemaild.setVisible(false);
				
		lblcliente.setVisible(true);
		lblasunto.setVisible(true);
		lblmensaje.setVisible(true);
		txtdestino.setVisible(true);
		String em= txtemail.getText();
		txtdestino.setText(em);
		txtasunto.setVisible(true);
		txtasunto.setText("Solicitud Reserva No. " + txtsolicitud.getText()+ " ,Apto. No." + txtnum.getText() + " Apartamentos Brasilia ");
		jSCP1.setVisible(true);
		txtAmensaje.setVisible(true);
		txtAmensaje.setEnabled(true);
		String me=  txtmsgdisp.getText()+ " , LLAMENOS AL 950240011 O ENVIENOS EMAIL CON SU NÚMERO DE TELEFONO CON EL FIN DE ULTIMAR DATOS DE LA RESERVA";
		txtAmensaje.setText(me);
		btnenviar.setVisible(true);
		
		
        }//GEN-LAST:event_chbemailaItemStateChanged
Correo c = new Correo();
        private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
                // TODO add your handling code here:
		
		
		 c.setContrasenia("ebfwndfprykkhrqy");
	 c.setUsuarioCorreo("aptosbrasilia@gmail.com");
	c.setAsunto(txtasunto.getText());
	 c.setMensaje(txtAmensaje.getText());
	 c.setDestino(txtdestino.getText().trim());
	 c.setNombreArchivo("");
	 c.setRutaArchivo("");
	 fsolicitudesweb func = new fsolicitudesweb();
		 if (func.enviarCorreo(c)) {
		 JOptionPane.showMessageDialog(null, "Envio Exitoso");
		 
		 
		 vsolicitudesweb dts = new vsolicitudesweb();
		 dts.setIdSolicitud(Integer.parseInt(txtsolicitud.getText()));
                 dts.setEstado("Gestionada");
		 func.editar(dts);
		 dispose();
		 }else{
			 JOptionPane.showMessageDialog(null, "Error al enviar");
			dispose(); 
		 }
		
        }//GEN-LAST:event_btnenviarActionPerformed

        private void chbemaildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbemaildActionPerformed
                // TODO add your handling code here:
		dispose();
        }//GEN-LAST:event_chbemaildActionPerformed

        private void chbemailaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbemailaMouseClicked
                // TODO add your handling code here:
		chbdispo.setVisible(false);
		chbemaila.setSelected(true);
        }//GEN-LAST:event_chbemailaMouseClicked

        private void chbemailaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbemailaActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_chbemailaActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmGestionweb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmGestionweb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmGestionweb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmGestionweb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmGestionweb().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnenviar;
        private javax.swing.JCheckBox chbdispo;
        private javax.swing.JCheckBox chbemaila;
        private javax.swing.JCheckBox chbemaild;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JScrollPane jSCP1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel lblasunto;
        private javax.swing.JLabel lblcliente;
        private javax.swing.JLabel lblmensaje;
        private javax.swing.JTextArea txtAmensaje;
        public static javax.swing.JTextField txtFein;
        private javax.swing.JTextField txtasunto;
        private javax.swing.JTextField txtdestino;
        public static javax.swing.JTextField txtemail;
        public static javax.swing.JTextField txtfesa;
        public static javax.swing.JTextField txtidaparta;
        private javax.swing.JTextField txtmsgdisp;
        public static javax.swing.JTextField txtnum;
        public static javax.swing.JTextField txtsolicitud;
        public static javax.swing.JTextField txttipo;
        // End of variables declaration//GEN-END:variables
}
