
package Presentacion;


import Datos.vgastos;
import Logica.Conexion;
import Logica.fgastos;

import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author inesm
 */
 class frmgastos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmcliente
     */
    public frmgastos() {
        initComponents();
         mostrar("");
        inhabilitar();

    }
 private String accion = "guardar";

    void ocultar_columnas() {
        tablalistado.getColumnModel().getColumn(0).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(0).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        tablalistado.getColumnModel().getColumn(1).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(1).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(1).setPreferredWidth(0);
    }

    void inhabilitar() {
        
        txtidgasto.setVisible(false);
        txtnumapartamento.setEnabled(false);
        txtmaterial.setEnabled(false);
        txtprecio.setEnabled(false);
        txtcantidad.setEnabled(false);
        txtgastado.setEnabled(false);
         txtidapartamento.setEnabled(false);
          txtreparacion.setEnabled(false);
          dcfechagasto.setEnabled(false);
        btnguardar.setEnabled(false);
        btnbuscaapartamento.setEnabled(false);
        btncancelar.setEnabled(false);
        btneliminar.setEnabled(false);
       txtidapartamento.setVisible(false);
        btnguardar.setEnabled(false);
        btncancelar.setEnabled(false);
        btneliminar.setEnabled(false);
        txtidgasto.setText("");
        txtmaterial.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
        txtmaterial.setText("");
       txtreparacion.setText("");
       
    }

    void habilitar() {
        
          txtidgasto.setVisible(false);
          txtnumapartamento.setVisible(true);
           btnbuscaapartamento.setEnabled(true);
        txtmaterial.setEnabled(true);
        txtprecio.setEnabled(true);
        txtcantidad.setEnabled(true);
        txtgastado.setEnabled(true);
          txtidapartamento.setEnabled(false);
          txtreparacion.setEnabled(true);
          dcfechagasto.setEnabled(true);
        btnguardar.setEnabled(true);
        btncancelar.setEnabled(true);
        btneliminar.setEnabled(true);
         txtmaterial.setVisible(true);
        txtprecio.setVisible(true);
        txtcantidad.setVisible(true);
        txtgastado.setVisible(true);
        txtidgasto.setText("");
        txtmaterial.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
      txtreparacion.setText("");
    }

    void mostrar(String buscar) {

        try {
            DefaultTableModel modelo;
            fgastos func = new fgastos();
            modelo = func.mostrar(buscar);
            tablalistado.setModel(modelo);
            ocultar_columnas();
            lbltotalregistros.setText("Total Registros: " + Integer.toString(func.totalregistros));
            lbltotaldegastos.setText("Total de Gastos: " +func.totaldegastos);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jDateChooser1 = new com.toedter.calendar.JDateChooser();
                jPanel3 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                txtmaterial = new javax.swing.JTextField();
                btnnuevo = new javax.swing.JButton();
                btnguardar = new javax.swing.JButton();
                btncancelar = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                txtidgasto = new javax.swing.JTextField();
                jLabel13 = new javax.swing.JLabel();
                txtprecio = new javax.swing.JTextField();
                txtcantidad = new javax.swing.JTextField();
                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                txtnumapartamento = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                txtreparacion = new javax.swing.JTextArea();
                jLabel8 = new javax.swing.JLabel();
                dcfechagasto = new com.toedter.calendar.JDateChooser();
                jLabel5 = new javax.swing.JLabel();
                txtgastado = new javax.swing.JTextField();
                txtidapartamento = new javax.swing.JTextField();
                btnbuscaapartamento = new javax.swing.JButton();
                listadoapartamentos = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txtbuscar = new javax.swing.JTextField();
                btnbuscar = new javax.swing.JButton();
                btneliminar = new javax.swing.JButton();
                btnsalir = new javax.swing.JButton();
                lbltotalregistros = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                btnreporte = new javax.swing.JButton();
                lbltotaldegastos = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tablalistado = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();

                setBackground(new java.awt.Color(0, 153, 153));
                setClosable(true);
                setIconifiable(true);
                setMaximizable(true);
                setAutoscrolls(true);
                setMaximumSize(new java.awt.Dimension(1064, 768));
                setMinimumSize(new java.awt.Dimension(768, 768));
                setPreferredSize(new java.awt.Dimension(1064, 768));

                jPanel3.setBackground(new java.awt.Color(204, 204, 204));
                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Gastos por Apartamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 16), new java.awt.Color(0, 153, 204))); // NOI18N
                jPanel3.setForeground(new java.awt.Color(204, 204, 204));
                jPanel3.setToolTipText("");

                jLabel4.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(0, 153, 204));
                jLabel4.setText("Material:");
                jLabel4.setToolTipText("");

                txtmaterial.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtmaterialActionPerformed(evt);
                        }
                });

                btnnuevo.setBackground(new java.awt.Color(102, 102, 102));
                btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/app.png"))); // NOI18N
                btnnuevo.setText("Nuevo");
                btnnuevo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnnuevoActionPerformed(evt);
                        }
                });

                btnguardar.setBackground(new java.awt.Color(102, 102, 102));
                btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/folder.png"))); // NOI18N
                btnguardar.setText("Guardar");
                btnguardar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnguardarActionPerformed(evt);
                        }
                });

                btncancelar.setBackground(new java.awt.Color(102, 102, 102));
                btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/error.png"))); // NOI18N
                btncancelar.setText("Cancelar");
                btncancelar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btncancelarActionPerformed(evt);
                        }
                });

                jLabel3.setBackground(new java.awt.Color(204, 204, 204));
                jLabel3.setForeground(new java.awt.Color(153, 153, 153));
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/Brasilia13.png"))); // NOI18N
                jLabel3.setMaximumSize(new java.awt.Dimension(174, 38));
                jLabel3.setMinimumSize(new java.awt.Dimension(174, 38));
                jLabel3.setPreferredSize(new java.awt.Dimension(174, 238));

                jLabel13.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                jLabel13.setForeground(new java.awt.Color(0, 153, 204));
                jLabel13.setText("Precio:");
                jLabel13.setToolTipText("");

                txtprecio.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtprecioActionPerformed(evt);
                        }
                });

                txtcantidad.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtcantidadActionPerformed(evt);
                        }
                });

                jLabel14.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(0, 153, 204));
                jLabel14.setText("Cantidad:");
                jLabel14.setToolTipText("");

                jLabel15.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                jLabel15.setForeground(new java.awt.Color(0, 153, 204));
                jLabel15.setToolTipText("");

                jLabel6.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(0, 153, 204));
                jLabel6.setText("Apartamento:");

                jLabel7.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(0, 153, 204));
                jLabel7.setText("Reparación:");

                txtreparacion.setColumns(20);
                txtreparacion.setRows(5);
                jScrollPane2.setViewportView(txtreparacion);

                jLabel8.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(0, 153, 204));
                jLabel8.setText("Fecha del Gasto:");

                jLabel5.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(0, 153, 204));
                jLabel5.setText("Total Gastado:");

                txtidapartamento.setToolTipText("");

                btnbuscaapartamento.setText("...");
                btnbuscaapartamento.setToolTipText("");
                btnbuscaapartamento.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnbuscaapartamentoActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(335, 335, 335))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtidapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addComponent(txtnumapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(161, 161, 161))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtidgasto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(256, 256, 256)
                                                        .addComponent(btnbuscaapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtmaterial, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                        .addComponent(btnnuevo)
                                                                        .addGap(59, 59, 59)
                                                                        .addComponent(btnguardar)))
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(dcfechagasto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                        .addGap(46, 46, 46)
                                                                        .addComponent(btncancelar)
                                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtgastado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(txtidgasto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)))
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtidapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtnumapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnbuscaapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dcfechagasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtprecio))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtgastado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnnuevo)
                                        .addComponent(btnguardar)
                                        .addComponent(btncancelar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                listadoapartamentos.setBackground(new java.awt.Color(204, 204, 204));
                listadoapartamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Listado de Gastos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 16), new java.awt.Color(0, 153, 204))); // NOI18N

                jLabel2.setBackground(new java.awt.Color(204, 204, 204));
                jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 153, 204));
                jLabel2.setText("Buscar:");
                jLabel2.setToolTipText("");

                txtbuscar.setBackground(new java.awt.Color(187, 187, 187));
                txtbuscar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtbuscarActionPerformed(evt);
                        }
                });

                btnbuscar.setBackground(new java.awt.Color(102, 102, 102));
                btnbuscar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
                btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/search.png"))); // NOI18N
                btnbuscar.setText("Buscar");
                btnbuscar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnbuscarActionPerformed(evt);
                        }
                });

                btneliminar.setBackground(new java.awt.Color(102, 102, 102));
                btneliminar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
                btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/garbage.png"))); // NOI18N
                btneliminar.setText("Eliminar");
                btneliminar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btneliminarActionPerformed(evt);
                        }
                });

                btnsalir.setBackground(new java.awt.Color(102, 102, 102));
                btnsalir.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
                btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/salida2.png"))); // NOI18N
                btnsalir.setText("Salir");
                btnsalir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnsalirActionPerformed(evt);
                        }
                });

                lbltotalregistros.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                lbltotalregistros.setForeground(new java.awt.Color(102, 102, 102));
                lbltotalregistros.setText("Registros");

                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/Brasilia13.png"))); // NOI18N

                btnreporte.setBackground(new java.awt.Color(102, 102, 102));
                btnreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/reportes.png"))); // NOI18N
                btnreporte.setText("Reporte");
                btnreporte.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnreporteActionPerformed(evt);
                        }
                });

                lbltotaldegastos.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                lbltotaldegastos.setForeground(new java.awt.Color(102, 102, 102));
                lbltotaldegastos.setText("Total de  Gastos:");

                tablalistado.setBackground(new java.awt.Color(204, 204, 204));
                tablalistado.setForeground(new java.awt.Color(102, 102, 102));
                tablalistado.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tablalistado.setGridColor(new java.awt.Color(102, 102, 102));
                tablalistado.setInheritsPopupMenu(true);
                tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tablalistadoMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tablalistado);

                javax.swing.GroupLayout listadoapartamentosLayout = new javax.swing.GroupLayout(listadoapartamentos);
                listadoapartamentos.setLayout(listadoapartamentosLayout);
                listadoapartamentosLayout.setHorizontalGroup(
                        listadoapartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listadoapartamentosLayout.createSequentialGroup()
                                .addGroup(listadoapartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(listadoapartamentosLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)
                                                .addComponent(lbltotaldegastos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, listadoapartamentosLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(listadoapartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(listadoapartamentosLayout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnbuscar)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnreporte)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btneliminar)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane1))
                                                .addGap(2, 2, 2)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                listadoapartamentosLayout.setVerticalGroup(
                        listadoapartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listadoapartamentosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32)
                                .addGroup(listadoapartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnbuscar)
                                        .addComponent(btneliminar)
                                        .addComponent(btnsalir)
                                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(btnreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(listadoapartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbltotalregistros)
                                        .addComponent(lbltotaldegastos))
                                .addGap(51, 51, 51))
                );

                lbltotaldegastos.getAccessibleContext().setAccessibleParent(lbltotaldegastos);

                jLabel1.setFont(new java.awt.Font("Dialog", 3, 21)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 153, 204));
                jLabel1.setText("Gastos:");
                jLabel1.setToolTipText("");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listadoapartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(listadoapartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                listadoapartamentos.getAccessibleContext().setAccessibleDescription("");

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked
        // TODO add your handling code here:
        btnguardar.setText("Editar");
        habilitar();
        btneliminar.setEnabled(true);
        accion="editar";

        int fila=tablalistado.rowAtPoint(evt.getPoint());
        txtidgasto.setText(tablalistado.getValueAt(fila, 0).toString());
         txtidapartamento.setText(tablalistado.getValueAt(fila, 1).toString());
         txtnumapartamento.setText(tablalistado.getValueAt(fila, 2).toString());
         dcfechagasto.setDate(Date.valueOf(tablalistado.getValueAt(fila, 3).toString()));
        txtmaterial.setText(tablalistado.getValueAt(fila,4).toString());
         txtcantidad.setText(tablalistado.getValueAt(fila, 5).toString());
          txtreparacion.setText(tablalistado.getValueAt(fila,6).toString());
        txtprecio.setText(tablalistado.getValueAt(fila, 7).toString());
        txtgastado.setText(tablalistado.getValueAt(fila, 8).toString());
       
    }//GEN-LAST:event_tablalistadoMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:

        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (!txtidgasto.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de ELIMINAR el Gasto?", "Confirmar", 2);

            if (confirmacion==0){
                fgastos func= new fgastos();
                vgastos dts= new vgastos();

                dts.setIdgastos(Integer.parseInt(txtidgasto.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }

        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
        txtbuscar.transferFocus();
    }//GEN-LAST:event_txtbuscarActionPerformed
    private Connection connection = new Conexion().conectar();
    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
        // TODO add your handling code here:
        
           Map p= new HashMap();
       JasperReport report;
       JasperPrint print;
          
        try {
            report =JasperCompileManager.compileReport(new File("").getAbsolutePath()+
                    "/src/Reportes/rptGastos.jrxml");
            print=JasperFillManager.fillReport(report,p,connection);
            JasperViewer view = new JasperViewer(print,false);
            view.setTitle("Listado de Gastos por Apartamentos");
            view.setVisible(true);
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnreporteActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
        txtcantidad.transferFocus();
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
        double totg= 0.00;
        double prec;
        int can;
        can = Integer.parseInt(txtcantidad.getText());
        prec=Double.parseDouble(txtprecio.getText());
        totg= can*prec;
        txtgastado.setText(String.valueOf(totg));
        txtprecio.transferFocus();
    }//GEN-LAST:event_txtprecioActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        inhabilitar();
        jLabel2.transferFocus();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:

        if (txtmaterial.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un Material");
            txtmaterial.requestFocus();
            return;
        }
        if (txtprecio.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un Precio del Material");
            txtprecio.requestFocus();
            return;
        }
        if (txtcantidad.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una Cantidad del Material");
            txtcantidad.requestFocus();
            return;
        }
        if (txtreparacion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un motivo de compra del Material");
            txtreparacion.requestFocus();
            return;
        }
       
        vgastos dts = new vgastos();
        fgastos func = new fgastos();
        
        dts.setIdapartamento(Integer.parseInt(txtidapartamento.getText()));
         Calendar cal, cal1, cal2;
        int d, m, a;
        cal = dcfechagasto.getCalendar();
        d = cal.get(Calendar.DAY_OF_MONTH);
        m = cal.get(Calendar.MONTH);
        a = cal.get(Calendar.YEAR) - 1900;
        Date fg = new Date(a, m, d);
        dts.setFecha_gasto(fg);
        dts.setMaterial(txtmaterial.getText());
        dts.setCantidad(Integer.parseInt(txtcantidad.getText()));
        dts.setReparacion(txtreparacion.getText());
        dts.setPrecio(Double.parseDouble(txtprecio.getText()));
        
        dts.setTotalgastado(Double.parseDouble(txtgastado.getText()));
      
        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showConfirmDialog(rootPane, "El Gasto fue registrado satisfactoriamente");
                mostrar("");
                inhabilitar();
            }

        } else if (accion.equals("editar")) {
            dts.setIdgastos(Integer.parseInt(txtidgasto.getText()));

            if (func.editar(dts)) {
                JOptionPane.showConfirmDialog(rootPane, "El Gasto fue editado satisfactoriamente");
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnguardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaterialActionPerformed
        // TODO add your handling code here:
        txtmaterial.transferFocus();
    }//GEN-LAST:event_txtmaterialActionPerformed

    private void btnbuscaapartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaapartamentoActionPerformed
        // TODO add your handling code here:
        frmvistaapartamentog form = new frmvistaapartamentog();
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnbuscaapartamentoActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmgastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmgastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmgastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmgastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmgastos().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnbuscaapartamento;
        private javax.swing.JButton btnbuscar;
        private javax.swing.JButton btncancelar;
        private javax.swing.JButton btneliminar;
        private javax.swing.JButton btnguardar;
        private javax.swing.JButton btnnuevo;
        private javax.swing.JButton btnreporte;
        private javax.swing.JButton btnsalir;
        private com.toedter.calendar.JDateChooser dcfechagasto;
        private com.toedter.calendar.JDateChooser jDateChooser1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel lbltotaldegastos;
        private javax.swing.JLabel lbltotalregistros;
        private javax.swing.JPanel listadoapartamentos;
        private javax.swing.JTable tablalistado;
        private javax.swing.JTextField txtbuscar;
        private javax.swing.JTextField txtcantidad;
        private javax.swing.JTextField txtgastado;
        public static javax.swing.JTextField txtidapartamento;
        private javax.swing.JTextField txtidgasto;
        private javax.swing.JTextField txtmaterial;
        public static javax.swing.JTextField txtnumapartamento;
        private javax.swing.JTextField txtprecio;
        private javax.swing.JTextArea txtreparacion;
        // End of variables declaration//GEN-END:variables
}
