/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.vsolicitudescalls;
import Logica.Conexion;
import Logica.fsolicitudesCalls;
import static Presentacion.frmSolicitudesCalls.idtrabajador;
import java.io.File;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;



import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author inesm
 */
public class frmSolicitudesCalls extends javax.swing.JInternalFrame {

	/**
	 * Creates new form solicitud
	 */
	public frmSolicitudesCalls() {
		initComponents();
		mostrar("");
	}
  void ocultar_columnas() {
        tablalistado.getColumnModel().getColumn(0).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(0).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(0).setPreferredWidth(0);
	
	tablalistado.getColumnModel().getColumn(6).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(6).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(6).setPreferredWidth(0);
    }

    void mostrar(String buscar) {

        try {
            DefaultTableModel modelo;
            fsolicitudesCalls func = new fsolicitudesCalls();
            modelo = func.mostrar(buscar);
            tablalistado.setModel(modelo);
            ocultar_columnas();
	    idtrabajador.setEnabled(false);
	    idtrabajador.setVisible(false);
	     txttrabajador.setEnabled(false);
	    txttrabajador.setVisible(false);
            lbltotalregistros.setText("Total Registros: " + Integer.toString(func.totalregistros));
	      } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                txtidtrabajador = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                txtbuscar = new javax.swing.JTextField();
                btnbuscar = new javax.swing.JButton();
                btngestionar = new javax.swing.JButton();
                btneliminar = new javax.swing.JButton();
                btnreporte = new javax.swing.JButton();
                btnsalir = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tablalistado = new javax.swing.JTable();
                lbltotalregistros = new javax.swing.JLabel();
                idtrabajador = new javax.swing.JTextField();
                txttrabajador = new javax.swing.JTextField();
                btncompreserva = new javax.swing.JButton();

                setClosable(true);
                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setIconifiable(true);
                setMaximizable(true);
                setResizable(true);

                txtidtrabajador.setBackground(new java.awt.Color(204, 204, 204));
                txtidtrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solicitudes Telefónicas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 14), new java.awt.Color(0, 153, 204)))); // NOI18N

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/Brasilia13.png"))); // NOI18N

                jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 153, 204));
                jLabel2.setText("Buscar Solicitud:");

                btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/search.png"))); // NOI18N
                btnbuscar.setText("Buscar");
                btnbuscar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnbuscarActionPerformed(evt);
                        }
                });

                btngestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/phone-call(3).png"))); // NOI18N
                btngestionar.setText("Gestionar");
                btngestionar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btngestionarActionPerformed(evt);
                        }
                });

                btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/garbage.png"))); // NOI18N
                btneliminar.setText("Eliminar");
                btneliminar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btneliminarActionPerformed(evt);
                        }
                });

                btnreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/reportes.png"))); // NOI18N
                btnreporte.setText("Reporte");
                btnreporte.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnreporteActionPerformed(evt);
                        }
                });

                btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/exit.png"))); // NOI18N
                btnsalir.setText("Salir");
                btnsalir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnsalirActionPerformed(evt);
                        }
                });

                tablalistado.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(tablalistado);

                lbltotalregistros.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                lbltotalregistros.setForeground(new java.awt.Color(102, 102, 102));
                lbltotalregistros.setText("Registros:");

                btncompreserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/printer.png"))); // NOI18N
                btncompreserva.setText(" Comprobante");
                btncompreserva.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btncompreservaActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout txtidtrabajadorLayout = new javax.swing.GroupLayout(txtidtrabajador);
                txtidtrabajador.setLayout(txtidtrabajadorLayout);
                txtidtrabajadorLayout.setHorizontalGroup(
                        txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtidtrabajadorLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                                .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(idtrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(23, 23, 23))
                                                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btngestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnreporte)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                                                .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                                                                .addComponent(btncompreserva, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtidtrabajadorLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(txttrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                .addComponent(btneliminar))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtidtrabajadorLayout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
                );
                txtidtrabajadorLayout.setVerticalGroup(
                        txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(idtrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnsalir))))
                                        .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                                .addGap(98, 98, 98)
                                                .addComponent(txttrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(txtidtrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnbuscar)
                                                        .addComponent(btngestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(txtidtrabajadorLayout.createSequentialGroup()
                                                        .addComponent(btneliminar)
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                        .addComponent(btncompreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(lbltotalregistros)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtidtrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtidtrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
                // TODO add your handling code here:
		  mostrar(txtbuscar.getText());
        }//GEN-LAST:event_btnbuscarActionPerformed
private Connection connection = new Conexion().conectar();
        private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
                // TODO add your handling code here:
		  Map p= new HashMap();
                JasperReport report;
                JasperPrint print;

                try {
                        report =JasperCompileManager.compileReport(new File("").getAbsolutePath()+
                                "/src/Reportes/rptsolicitudesCalls.jrxml");
                        print=JasperFillManager.fillReport(report,p,connection);
                        JasperViewer view = new JasperViewer(print,false);
                        view.setTitle("Listado de Solicitudes-Reservas Recibidas por Telefóno");
                        view.setVisible(true);

                } catch (Exception e) {

                        e.printStackTrace();
                }
                                          
        }//GEN-LAST:event_btnreporteActionPerformed

        private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
                // TODO add your handling code here:
       int fila = tablalistado.getSelectedRow();
		if (!(tablalistado.getValueAt(fila, 0).equals(""))) {
                        int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de ELIMINAR la Solicitud", "Confirmar", 2);
			
                        if (confirmacion==0){
                                fsolicitudesCalls func= new fsolicitudesCalls();
                                vsolicitudescalls dts= new vsolicitudescalls();

                                dts.setIdllamada(Integer.parseInt(tablalistado.getValueAt(fila, 0).toString()));
                                func.eliminar(dts);
                                mostrar("");
                                
                        }
		}
                
                            
        }//GEN-LAST:event_btneliminarActionPerformed

        private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
                // TODO add your handling code here:
		 this.dispose();
        }//GEN-LAST:event_btnsalirActionPerformed

        private void btngestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestionarActionPerformed
                // TODO add your handling code here:
		frmGestionCalls form = new frmGestionCalls();
		frmInicio.escritorio.add(form);
		form.toFront();
		form.setVisible(true);
		frmGestionCalls.txtidtrabajador.setText(idtrabajador.getText());
 frmGestionCalls.txttrabajador.setText(txttrabajador.getText());


		 vsolicitudescalls dts2 = new vsolicitudescalls();
        fsolicitudesCalls func2 = new fsolicitudesCalls();
        int d = func2.buscid(dts2);
 
	frmGestionCalls.txtidllamada.setText(String.valueOf(d));
	Date fecha = new Date();
	 
	frmGestionCalls.dcFechasol.setDate(fecha);
	
	frmGestionCalls.txtTelfllaman.transferFocus();
        }//GEN-LAST:event_btngestionarActionPerformed

        private void btncompreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompreservaActionPerformed
                // TODO add your handling code here:
		  int fila = tablalistado.getSelectedRow();
		String idreser= tablalistado.getValueAt(fila, 10).toString();
		  frmEnviarCompReserva form = new frmEnviarCompReserva();
		frmInicio.escritorio.add(form);
		form.toFront();
		form.setVisible(true);
		 frmEnviarCompReserva.txtidreserva.setText((idreser));
		 
        fsolicitudesCalls func6 = new fsolicitudesCalls();
		String em= func6.buscemail(Integer.parseInt(tablalistado.getValueAt(fila, 9).toString()));
		frmEnviarCompReserva.txtemail.setText(em);
        }//GEN-LAST:event_btncompreservaActionPerformed

	
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmSolicitudesCalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmSolicitudesCalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmSolicitudesCalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmSolicitudesCalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmSolicitudesCalls().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnbuscar;
        private javax.swing.JButton btncompreserva;
        private javax.swing.JButton btneliminar;
        private javax.swing.JButton btngestionar;
        private javax.swing.JButton btnreporte;
        private javax.swing.JButton btnsalir;
        public static javax.swing.JTextField idtrabajador;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lbltotalregistros;
        private javax.swing.JTable tablalistado;
        private javax.swing.JTextField txtbuscar;
        private javax.swing.JPanel txtidtrabajador;
        public static javax.swing.JTextField txttrabajador;
        // End of variables declaration//GEN-END:variables
}
