-- MySQL Script generated by MySQL Workbench
-- 12/05/16 18:33:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema basereserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basereserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basereserva` DEFAULT CHARACTER SET utf8 ;
USE `basereserva` ;

-- -----------------------------------------------------
-- Table `basereserva`.`Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`Apartamento` (
  `idApartamento` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(3) NOT NULL,
  `piso` VARCHAR(2) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `Caracteristicas` VARCHAR(512) NULL DEFAULT NULL,
  `preciodbaja` DECIMAL(5,2) NOT NULL,
  `preciodalta` DECIMAL(5,2) NOT NULL,
  `Estado` VARCHAR(15) NOT NULL,
  `tipo_Apartamento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idApartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`DP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`DP` (
  `idDP` INT NOT NULL AUTO_INCREMENT,
  `periodo` INT(4) NOT NULL,
  `valor` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`idDP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`Persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `PrimerApellido` VARCHAR(45) NOT NULL,
  `SegundApellido` VARCHAR(20) NOT NULL,
  `tipo_documento` VARCHAR(15) NOT NULL,
  `num_documento` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`Cliente` (
  `codigo_cliente` VARCHAR(10) NOT NULL,
  `idpersona` INT NOT NULL,
  UNIQUE INDEX `codigo_cliente_UNIQUE` (`codigo_cliente` ASC),
  INDEX (`idpersona` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`idpersona`)
    REFERENCES `basereserva`.`Persona` (`idpersona`)
    ON DELETE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`trabajador` (
  `idpersona` INT NOT NULL,
  `acceso` VARCHAR(15) NOT NULL,
  `login` VARCHAR(15) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  CONSTRAINT `fk_persona_trabajador`
    FOREIGN KEY (`idpersona`)
    REFERENCES `basereserva`.`Persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`consumo` (
  `idconsumo` INT NOT NULL AUTO_INCREMENT,
  `idreserva` INT NOT NULL,
  `idapartamento` INT NOT NULL,
  `periodo` VARCHAR(22) NOT NULL,
  `precio` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idconsumo`),
  INDEX `fk_consumo_reserva_idx` (`idreserva` ASC),
  INDEX `fk_consumo_Apartamento_idx` (`idapartamento` ASC),
  CONSTRAINT `fk_consumo_reserva`
    FOREIGN KEY (`idreserva`)
    REFERENCES `basereserva`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_Apartamento`
    FOREIGN KEY (`idapartamento`)
    REFERENCES `basereserva`.`Apartamento` (`idApartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basereserva`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basereserva`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `idreserva` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `num_comprobante` VARCHAR(20) NOT NULL,
  `total_pago` DECIMAL(7,2) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `iva` INT NOT NULL,
  `tipo_pago` VARCHAR(20) NOT NULL,
  `num_tarjeta` VARCHAR(11) NULL DEFAULT NULL,
  `estado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_reserva_idx` (`idreserva` ASC),
  INDEX `fk_pago_consumo_idx` (),
  CONSTRAINT `fk_pago_reserva`
    FOREIGN KEY (`idreserva`)
    REFERENCES `basereserva`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_consumo`
    FOREIGN KEY ()
    REFERENCES `basereserva`.`consumo` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
